---

logstash_yum_repository: "{{logstash_repo_baseurl}}/yum"

logstash_yum_config: |
  [logstash-{{logstash_version}}]
  name=Logstash repository for {{logstash_version}} packages
  baseurl={{logstash_yum_repository}}
  gpgcheck=1
  gpgkey={{logstash_gpg_key}}
  enabled=1

logstash_packages:
  - logstash

logstash_defaults_cfg: /etc/sysconfig/logstash

# vi:ts=2:sw=2:et:ft=yaml
