---
galaxy_info:
  author: Emiliano Castagnari
  description: Ansible role for Logstash
  license: Apache
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
      - 6
      - 7
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
    - wheezy
  galaxy_tags:
    - monitoring
    - system

dependencies: []

