---
# defaults file for ansible-consul
consul_bin_path: '/usr/local/bin'
consul_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + consul_bind_interface]['ipv4']['address'] }}"
consul_bind_interface: 'enp0s8' # Define interface to bind to...(eth0|eth1|enp0s8)
consul_client_address: '0.0.0.0'  #defines client address to listen on...either set to 0.0.0.0 (default) or consul_bind_address var.
consul_clients_group: 'consul-clients'  #defines Ansible group that nodes belong to which are clients (agents or services running on)
consul_config_dir: '/etc/consul.d'
consul_config_file: '/etc/consul.conf'
consul_data_dir: '/var/consul'
consul_datacenter: 'dc1'  #defines datacenter name for Consul
consul_dl_file: 'consul_{{ consul_version }}_linux_amd64.zip'
consul_dl_url: 'https://releases.hashicorp.com/consul/{{ consul_version }}'
consul_enable_dnsmasq: true  #defines if dnsmasq should be installed and configured to resolv consul dns queries to port 8600
consul_encryption_key: 'qLLp1YCJzp9E/xhg11qkdQ=='  #generate using 'consul keygen'..make sure to generate a new key and replace this...
consul_group: 'consul'
consul_home: '/opt/consul'
consul_key_file: '/etc/consul.key'
consul_log_file: '/var/log/consul'
consul_master: 'node0'  #defines which node is the consul master
consul_mysql_password: 'consul'
consul_mysql_user: 'consul'
consul_servers_group: 'consul-servers'  #defines the Ansible group which contains the consul server(s)
consul_ui_dl_file: 'consul_{{ consul_version }}_web_ui.zip'
consul_user: 'consul'
consul_version: '0.6.3'
consul_services_mode: 0640



#