---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  tags: logstash_install

- include: config.yml
  tags: logstash_config

- include: plugins.yml
  tags: logstash_plugins

- name: Logstash start at boot time
  service:
    name=logstash
    enabled=yes

- name: create logstash db directory
  file:
    path: "/var/cache/logstash"
    state: directory
    owner: logstash
    group: logstash
    
- name: give logstash read to logs #setfacl -m u:logstash:r /var/log/messages
  shell: setfacl -m u:logstash:r /var/log/messages
  args:
   executable: /bin/bash
  
# vi:ts=2:sw=2:et:ft=yaml
