---

- name: Create Sensu API specific config
  template:
    src: config.json.j2
    dest: /etc/sensu/config_api.json
  notify:
    - Restart sensu-api {{ sensu_from }}
  tags:
    - sensu_config

- name: Create symlink to the main config for sensu-api
  file:
    src: /etc/sensu/config_api.json
    dest: /etc/sensu/config.json
    state: link
  when: >
    sensu_install_api and
    not sensu_install_server
  tags:
    - sensu_config

- name: Make sure sensu-api is enabled
  service:
    name: sensu-api
    enabled: yes
  tags:
    - sensu_config

- name: Make sure sensu-api is started
  service:
    name: sensu-api
    state: started
  register: sensu_service_api_started
  tags:
    - sensu_pkg
    - sensu_config
