---

- name: Create Sensu server specific config
  template:
    src: config.json.j2
    dest: /etc/sensu/config_server.json
  notify:
    - Restart sensu-server {{ sensu_from }}
  tags:
    - sensu_config

- name: Create symlink to the main config for sensu-server
  file:
    src: /etc/sensu/config_server.json
    dest: /etc/sensu/config.json
    state: link
    force: yes
  tags:
    - sensu_config

- name: Make sure Sensu server service is enabled
  service:
    name: sensu-server
    enabled: yes
  tags:
    - sensu_config

- name: Make sure Sensu server service is started
  service:
    name: sensu-server
    state: started
  register: sensu_service_server_started
  tags:
    - sensu_pkg
    - sensu_config
